app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import uuid 
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import UserMixin
from flask_login import LoginManager
from flask_marshmallow import Marshmallow 


login_manager = LoginManager()
ma = Marshmallow()
db = SQLAlchemy()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    first_name = db.Column(db.String(150), nullable=True, default='')
    last_name = db.Column(db.String(150), nullable=True, default='')
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(150), nullable = False, default='')
    g_auth_verify = db.Column(db.Boolean, default=False)
    token = db.Column(db.String, unique=True, default='')
    date_created = db.Column(db.DateTime, nullable = False, default=datetime.utcnow)
    vehicle = db.relationship('Vehicle', backref='owner', lazy=True)
    
    def __init__(self, email, first_name='', last_name='', id = '',  password='', token='', g_auth_verify=False):
        self.id = self.set_id()
        self.email = email
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.token = self.set_token(10)
        self.g_auth_verify = g_auth_verify
        
    def set_token(self, length):
        return secrets.token_hex(length)
    
    def set_id(self):
        return str(uuid.uuid4())
    
    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
    
    def __repr__(self):
        return f'The user {self.email} has been added!'
    
class Vehicle(db.Model):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String(150), nullable=False, default='')
    make = db.Column(db.String(150), nullable=False, default='')
    model = db.Column(db.String(150), nullable=False, default='')
    color = db.Column(db.String(150), nullable=False, default='')
    year = db.Column(db.Numeric(precision=4))
    price = db.Column(db.Numeric(precision=10,scale=2))
    serial_num = db.Column(db.Numeric(precision=17))
    user_token = db.Column(db.String, db.ForeignKey(User.token), nullable=False)
    
    def __init__(self, make, model, color, year, price, serial_num, user_token, name, id=''):
        self.id = self.set_id()
        self.make = make
        self.model = model
        self.color = color
        self.year = year
        self.price = price
        self.serial_num = serial_num
        self.user_token = user_token
        self.name = name
        
    def __repr__(self):
        return f'The following vehicle has been added: {self.name}.'
    
    def set_id(self):
        return (secrets.token_urlsafe())
    
class VehicleSchema(ma.Schema):
    class Meta:
        fields = ['id', 'make', 'model','color','year','price', 'serial_num', 'name']
        
vehicle_schema = VehicleSchema()
vehicles_schema = VehicleSchema(many=True)

app/__init__.py
from flask import Flask
from config import Config
from .api.routes import api
from .site.routes import site
from .auth.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from .models import db, login_manager, ma
from flask_marshmallow import Marshmallow
from flask_cors import CORS
from app.helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.config.from_object(Config)

# Use the db instance created in models
db.init_app(app)

# Use the Migrate instance created in models
migrate = Migrate(app, db)

login_manager.init_app(app)
login_manager.login_view = 'home'

ma.init_app(app)

app.json_encoder = JSONEncoder

CORS(app)

from app import models

app/api/routes.py
from flask import Blueprint, request, jsonify
from app.helpers import token_required
from app.models import db,User,Vehicle,vehicle_schema,vehicles_schema

api = Blueprint('api', __name__, url_prefix= '/api')

@api.route('/getdata')
@token_required
def getdata(current_user_token):
    return { 'some': 'value' }

@api.route('/vehicles', methods=['POST'])
@token_required
def create_vehicle(current_user_token):
    name = request.json['name']
    make = request.json['make']
    model = request.json['model']
    color = request.json['color']
    year = request.json['year']
    price = request.json['price']
    serial_num = request.json['serial_num']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    
    vehicle = Vehicle(
        name=name,
        make=make,
        model=model,
        color=color,
        year=year,
        price=price,
        serial_num=serial_num,
        user_token=user_token
    )

    db.session.add(vehicle)
    db.session.commit()

    response = vehicle_schema.dump(vehicle)
    return jsonify(response)


@api.route('/vehicles/', methods=['GET'])
@token_required
def get_vehicles(current_user_token):
    owner = current_user_token.token
    vehicles = Vehicle.query.filter_by(user_token = owner).all()
    response = vehicles_schema.dump(vehicles)
    return jsonify(response)

@api.route('/vehicles/<id>', methods = ['GET'])
@token_required
def get_vehicle(current_user_token, id):
    owner = current_user_token.token
    vehicle = Vehicle.query.get(id)
    response = vehicle_schema.dump(vehicle)
    return jsonify(response)
    
    
@api.route('/vehicles/<id>', methods = ['POST', 'PUT'])
@token_required
def update_vehicle(current_user_token,id):
    vehicle = Vehicle.query.get(id)
    
    vehicle.name = request.json['name']
    vehicle.make = request.json['make']
    vehicle.model = request.json['model']
    vehicle.color = request.json['color']
    vehicle.year = request.json['year']
    vehicle.price = request.json['price']
    vehicle.serial_num = request.json['serial_num']
    vehicle.user_token = current_user_token.token
    
    db.session.commit()
    response = vehicle_schema.dump(vehicle)
    return jsonify(response)

@api.route('/vehicles/<id>', methods = ['DELETE'])
@token_required
def delete_vehicle(current_user_token, id):
    vehicle = Vehicle.query.get(id)
    db.session.delete(vehicle)
    db.session.commit()
    response = vehicle_schema.dump(vehicle)
    return jsonify(response)
    

app/site/routes.py
from flask import Blueprint, render_template
from app.models import Vehicle
from flask_login import current_user

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    vehicles = Vehicle.query.all()
    user_first_name = current_user.first_name if current_user.is_authenticated else None
    return render_template('index.html', vehicles=vehicles, user_first_name=user_first_name)

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="../../static/css/style.css">
    <title>Cars</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">Car Collections</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.sign_up')}}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>

{% block content %}
{% endblock %}
</body>
</html>

app/templates/form_entry.html
<form method="POST">
    {{ form.hidden_tag() }}
    
    <div class="form-group">
        <fieldset id="first-name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control", placeholder='Please enter your first name') }}
        </fieldset>
    </div>
    
    <div class="form-group">
        <fieldset id="last-name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control", placeholder='Please enter your last name') }}
        </fieldset>
    </div>

    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder='Please enter your email') }}
        </fieldset>
    </div>
    
    <div class="form-group">
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder='Please enter your password') }}
        </fieldset>
        <br>
        <div class="justify-content-center">
            {{ form.submit_button(class="btn btn-primary btn-block mt-1") }}
        </div>
    </div>
</form>

app/templates/signin_entry.html
<form method ="POST">
    {{ form.hidden_tag() }}
    <div class = "form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class= "form-control", placeholder='Please enter your email') }}
        </fieldset>
    </div>
    
    <div class="form-group">
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder='Please enter your password')}}
        </fieldset>
        <br>
        <div class = "justify-content-center">
            {{ form.submit_button(class = "btn btn-primary btn-block mt-1" )}}
        </div>
    </div>
</form>